sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_f90fd70c2ac1_key -iv $encrypted_f90fd70c2ac1_iv
    -in gce.json.enc -out gce.json -d
  - docker build -t sarunaskas/docker-test -f Dockerfile.dev .

script:
  - docker run sarunaskas/docker-test npm run test -- --coverage


deploy:
  provider: gae
  project: docker-test-231508
  keyfile: gce.json
  on: master
